# Kibana 인스턴스의 이름을 정의합니다. 주로 로깅이나 모니터링에서 Kibana 인스턴스를 식별하는 데 사용됩니다.
server.name: kibana

# Kibana 서버가 어떤 호스트 주소를 수신할지 결정합니다. '0.0.0.0'은 모든 사용 가능한 네트워크를 수신하겠다는 의미로, 외부에서의 접근을 허용합니다.
server.host: 0.0.0.0

# Kibana가 연결해야 할 Elasticsearch 클러스터의 주소를 지정합니다.
elasticsearch.hosts: ['http://elasticsearch:9200/']

# X-Pack 모니터링 UI에서 Elasticsearch 컨테이너를 활성화 합니다. Kibana에서 Elasticsearch 클러스터의 상태와 성능에 대한 모니터링 데이터를 시각적으로 확인할 수 있습니다.
xpack.monitoring.ui.container.elasticsearch.enabled: true

# Kibana가 Elasticsearch에 연결할 때 사용할 사용자 ID를 지정합니다.
elasticsearch.username: kibana_system

# Kibana가 Elasticsearch에 연결할 때 사용할 사용자 PW를 지정합니다.
elasticsearch.password: <YOUR KIBANA PASSWORD>
