# Logstash 서버가 어떤 호스트 주소를 수신할지 결정합니다. '0.0.0.0'은 모든 사용 가능한 네트워크를 수신하겠다는 의미로, 외부에서의 접근을 허용합니다.
http.host: '0.0.0.0'

# Logstash에게 모니터링 데이터를 보내는 Elasticsearch 클러스터의 주소를 지정합니다.
monitoring.elasticsearch.hosts: ['http://elasticsearch:9200/']

# Logstash가 Elasticsearch에 모니터링 데이터를 전송할 때 사용할 사용자 ID를 지정합니다.
monitoring.elasticsearch.username: <YOUR LOGSTASH ID>

# Logstash가 Elasticsearch에 모니터링 데이터를 전송할 때 사용할 사용자 PW를 지정합니다.
monitoring.elasticsearch.password: <YOUR LOGSTASH PASSWORD>
